### ISSUE TITLE
Hi，想咨询一下这个js有script标签这样的引入方式嘛？

### ISSUE THREAD

**Issue by melitigo** [ppz-pro/noty.js#2]
Hi，想咨询一下这个js有script标签这样的引入方式嘛？

**Comment by daGaiGuanYu** [comment]
可以参考这两个例子：
+ [内容比较乱、但样式全面](https://github.com/ppz-pro/noty.js/blob/b5c3504ca4e06014d355bcb0706d8648e0965147/docs/index.html#L98)
+ [几乎没样式，只有必要的内容](https://github.com/ppz-pro/noty.js/blob/b5c3504ca4e06014d355bcb0706d8648e0965147/docs/custom/index.html#L12)

这两个例子是通过 script 标签方式引入  
但需要使用 ```type="module"```，这种方式下，可以使用 import 关键字（不太旧的浏览器都支持）  

目前没做“不使用 type=module”的版本

**Comment by daGaiGuanYu** [comment]
现在可以了，哈哈哈，一年多了
``` html
<link rel="stylesheet" href="https://unpkg.com/@ppzp/noty/content/index.css">
<script src="https://unpkg.com/@ppzp/noty/global.js" type="module"></script>
```
